services:
  coffee-shop.database:
    image: postgres:16.8
    container_name: coffee-shop.database
    environment:
      - PGPORT=5433
      - POSTGRES_DB=CoffeeShop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  coffee-shop.seq:
    image: datalust/seq:latest
    container_name: coffee-shop.seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
      - "5431:5341"
      - "5340:80"

  coffee-shop.server:
    image: coffee-shop-server:latest
    container_name: coffee-shop.server
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    env_file: server/.env
    volumes:
      - server_logs:/logs
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      coffee-shop.database:
        condition: service_healthy
      coffee-shop.seq:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # coffee-shop.client:
  #   image: coffee-shop-client:latest
  #   container_name: coffee-shop.client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #   - "3000:80"
  #   depends_on:
  #     coffee-shop.server:
  #       condition: service_healthy

volumes:
  postgres_data:
  server_logs:
